<?php

/**
  * @file
  * islandora_bioinformatics_base.install
  */

/**
  * Implements hook_install().
  *
  * @see islandora_bioinformatics_base_islandora_required_objects()
  */
  function islandora_bioinformatics_base_install() {
    module_load_include('inc', 'islandora', 'includes/solution_packs');
    islandora_install_solution_pack('islandora_bioinformatics_base');
  }

/**
  * Implements hook_uninstall().
  */
  function islandora_bioinformatics_base_uninstall() {
    module_load_include('inc', 'islandora', 'includes/solution_packs');
    islandora_install_solution_pack('islandora_bioinformatics_base', 'uninstall');
    $variables = array('islandora_bioinformatics_base');
    array_walk($variables, 'variable_del');
  }


