<?php
/**
 * @file
 * Handles the uploading of the image file.
 */

/**
 * Defines a checkbox form used to assign people to projects
 *
 * @param array $form
 *   The Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 *
 * @return array
 *   The Drupal form definition.
 *
 *	Written by Quintin Dawson
 */
function islandora_bioinformatics_base_assign_person_to_project_form(array $form, array &$form_state) {
  
}

/**
 * Submit handler, creates a relation between the person an any selected objects.
 *
 * @param array $form
 *   The Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 */
function islandora_bioinformatics_base_assign_person_to_project_form_submit(array $form, array &$form_state) {
  
}
