<?php
/**
 * @file rel_cmodel_callbacks
 */


/**
 * @param FedoraObject $object
 * @param FedoraObject|null $cmodel
 */
function rel_cmodel_list($object, $cmodel=NULL) {
  /*
   * @TODO
   */
}

/**
 * @param FedoraObject $object
 * @param FedoraObject $cmodel
 */
function rel_cmodel_ingest($object, $cmodel) {
  /*
   * @TODO
   */
}

/**
 * @param FedoraObject $object
 * @param FedoraObject $target
 */
function rel_cmodel_add_rel($object, $target) {
  /*
   * @TODO
   */
}

/**
 * @param FedoraObject $object
 * @param FedoraObject $cmodel
 */
function rel_cmodel_add_rel_ui($object, $cmodel) {
  /*
   * @TODO
   */
}

/**
 * @param FedoraObject $object
 * @param FedoraObject $target
 */
function rel_cmodel_remove_rel($object, $target) {
  /*
   * @TODO
   */
}

/**
 * @param $object
 * @param $cmodel
 */
function rel_cmodel_remove_rel_ui($object, $cmodel, $target) {
  /*
   * @TODO
   */
}
